---
title: "Adult Income"
author: "Guillermo Hernández"
date: "March 17th"
output: html_document
params: 
  label: " <=50K" 
  age: 25
  work: "Public"
  ed: "Elementary School"
  race: " White"
  sex: " Male"
  hours: 40
---


```{r include=FALSE}
library(ggplot2)
library(ggpubr)
library(plotly)
library(dplyr)

data =  read.csv(url('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'), header=FALSE, sep=',')
colnames(data) = c('age','workclass','fnlwgt','education','education_num','marital_status','occupation','relationship','race','sex','cap_gain','cap_loss','hours_week','native_country','label')

# Some cleaning and selection of variables
data = data[complete.cases(data), ] %>% # Only data without NA
    select(age, workclass, education, race, sex, hours_week, label) %>%
    na.omit()

# Eliminating rows with ' ?' values
data = data[rowSums(data == " ?") == 0, , drop = FALSE]

# Checking the presence of NAs
NAcount = function(vector){
    return(sum(is.na(vector)))
}
if (sum(sapply(data, NAcount)) != 0){cat('ERROR: NAs detected.')}

# Just for quicker processing: removal of 70% of the data. I would not do this in a real application.
library(caret)
part = createDataPartition(data$label, p=0.8, list=FALSE)
data = data[part,]

#Modification of 'workclass'
levels(data$workclass) = c(levels(data$workclass), "Public", "Self Employed")
data$workclass = gsub('.*^\\ Self.*', 'Self Employed', data$workclass)
data$workclass = gsub('.*\\gov$.*', 'Public', data$workclass)
data$workclass = gsub('.*\\pay$.*', 'Without Pay', data$workclass)
#data$workclass = factor(data$workclass, levels = c(' Private', 'Public', 'Self Employed', 'Without Pay'))

#Modification of 'education'
levels(data$education) = c(levels(data$education), "Elementary school", "Middle School", "High School",'Unfinnished College')
data$education = gsub(' 1st-4th', 'Elementary School', data$education)
data$education = gsub(' 5th-6th', 'Middle School', data$education)
data$education = gsub(' 7th-8th', 'Middle School', data$education)
data$education = gsub(' 9th', 'High School', data$education)
data$education = gsub(' 10th', 'High School', data$education)
data$education = gsub(' 11th', 'High School', data$education)
data$education = gsub(' 12th', 'High School', data$education)
data$education = gsub(' Some-college', 'Unfinnished College', data$education)
data$education = gsub(' Assoc-voc', 'Assoc', data$education)
data$education = gsub(' Assoc-acdm', 'Assoc', data$education)
#data$education = factor(data$education)
#data$education = ordered(data$education, levels = c(' Preschool','Elementary School','Middle School','High School',' HS-grad',' Prof-school','Assoc','Unfinnished College',' Bachelors',' Masters',' Doctorate'))  

# Modification of 'race'
data$race = gsub(' Amer-Indian-Eskimo', 'Ind-Eskimo', data$race)
data$race = gsub(' Asian-Pac-Islander', 'Asian-Pac', data$race)

#data$sex = factor(data$sex, levels = c(' Male', ' Female'))

data = data[complete.cases(data), ]

dataPred = data %>% select(-label)
dataPred$label = ifelse(data$label == ' >50K', 1, 0)
```

# The Variables:

```{r echo=FALSE}
labs = c(params$label)
data = data %>% filter(label %in% labs)

ageplot = ggplot(data, aes(age, fill = label)) +
  geom_density(alpha = 0.5, kernel = "gaussian") +
  geom_vline(aes(xintercept = mean(age)), linetype = 2)+
  scale_fill_manual(name = "Label", values = c("firebrick3", "dodgerblue3")) +
  theme_minimal()+
  labs(title = "Age density plot by label", x = 'Age of Individual', y = 'Density')
    
hourplot = ggplot(data, aes(hours_week, fill = label)) +
  geom_density(alpha = 0.5, kernel = "gaussian") +
  geom_vline(aes(xintercept = mean(age)), linetype = 2)+
  scale_fill_manual(name = "Label", values = c("firebrick3", "dodgerblue3")) +
  theme_minimal()+
  labs(title = "Hour per Week density plot by label", x = 'Hours/Week Worked', y = 'Density')
  
edplot = ggplot(data, aes(x=education, fill=label)) +
  geom_bar(stat="count", width=0.7) +
  theme_minimal()+
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust = 1)) +
  scale_fill_manual(name = "Label", values = c("firebrick3", "dodgerblue3")) +
  labs(title = "Education barplot by label" , x = 'Hours/Week Worked', y = 'Density')
  
workplot = ggplot(data, aes(x=workclass, fill=label)) +
  geom_bar(stat="count", width=0.7) +
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust = 1)) +
  scale_fill_manual(name = "Label", values = c("firebrick3", "dodgerblue3")) +
  theme_minimal()+
  labs(title = "Workclass barplot by label" , x = 'Hours/Week Worked', y = 'Density')
  
sexplot = ggplot(data, aes(x=sex, fill=label)) +
  geom_bar(stat="count", width=0.7) +
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust = 1)) +
  scale_fill_manual(name = "Label", values = c("firebrick3", "dodgerblue3")) +
  theme_minimal() +
  labs(title = "Sex barplot by label" , x = 'Hours/Week Worked', y = 'Density')

raceplot = ggplot(data, aes(x=race, fill=label)) +
  geom_bar(stat="count", width=0.7) +
  theme(axis.text.x = element_text(angle = 45, vjust=1, hjust = 1)) +
  scale_fill_manual(name = "Label", values = c("firebrick3", "dodgerblue3")) +
  theme_minimal()+
  labs(title = "Race barplot by label" , x = 'Hours/Week Worked', y = 'Density')

ggplotly(ageplot)
ggplotly(hourplot)
ggplotly(edplot)
ggplotly(workplot)
ggplotly(sexplot)
ggplotly(raceplot)

```


# Predict your Income

This is the information you selected as predictors (if you did not, it is chosen as default):

```{r echo=FALSE, message = FALSE}
library(kableExtra)

mydata = data.frame( 'age'        = params$age,
                     'workclass'  = params$work,
                     'education'  = params$ed,
                     'race'       = params$race,
                     'sex'        = params$sex,
                     'hours_week' = params$hours)

model = glm(label~age+workclass+education+race+sex+hours_week, data=dataPred, family=binomial)
prediction = predict(model, newdata = mydata, type="response") 

kbl(mydata) %>% kable_material(c("striped", "hover"))
```

And the result was...

```{r echo = FALSE}
as.vector(ifelse(prediction < 0.5, 'It seems like you earn less than 50K...', 'You probably eran more than 50K a year, congratulations!'))
```

